export const ACTIONS = {
    ADDRESS_GET_OBJECTS : 'ADDRESS_GET_OBJECTS',
    ADDRESS_INPUT_CHANGED : 'ADDRESS_INPUT_CHANGED',
    ADDRESSES_SET_ERROR : 'ADDRESSES_SET_ERROR',
    ADDRESS_ON_SAVE_FORM : 'ADDRESS_ON_SAVE_FORM',
    ADDRESS_PREAPARE_FORM: 'ADDRESS_PREAPARE_FORM'
}